# Generated by Django 5.1.7 on 2025-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_welfare', '0004_profile_reset_code_profile_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('parrot', 'Parrot'), ('turtle', 'Turtle'), ('rabbit', 'Rabbit'), ('fish', 'Fish'), ('hamster', 'Hamster'), ('other', 'Other')], max_length=20),
        ),
    ]
