# Generated by Django 5.1.7 on 2025-05-06 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_welfare', '0006_remove_listing_last_seen_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listing_photos/')),
                ('is_main', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pet_welfare.listing')),
            ],
            options={
                'db_table': 'listing_photos',
                'ordering': ['-is_main', 'uploaded_at'],
            },
        ),
    ]
