swagger: '2.0'
info:
  title: Pet welfare app capstone API
  description: ''
  contact:
    email: shahen_hovakimyan@edu.aua.am
  license:
    name: BSD License
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization:
      Bearer {token}"'
security:
- Bearer: []
paths: {}
definitions: {}
