swagger: '2.0'
info:
  title: Pet welfare app capstone API
  description: ''
  contact:
    email: shahen_hovakimyan@edu.aua.am
  license:
    name: BSD License
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /api
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization:
      Bearer {token}"'
security:
- Bearer: []
paths:
  /login:
    post:
      operationId: login_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Login'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Login'
      tags:
      - login
    parameters: []
  /password-reset:
    post:
      operationId: password-reset_create
      description: Send reset code to user's email
      parameters:
      - name: data
        in: body
        required: true
        schema:
          required:
          - email
          type: object
          properties:
            email:
              type: string
      responses:
        '200':
          description: Reset code/link sent
          examples:
            application/json:
              message: Password reset code has been sent to your email.
              identifier: encoded_pk
      tags:
      - password-reset
    parameters: []
  /password-reset-confirm/{encoded_pk}/{token}:
    post:
      operationId: password-reset-confirm_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/PasswordResetConfirm'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/PasswordResetConfirm'
      tags:
      - password-reset-confirm
    parameters:
    - name: encoded_pk
      in: path
      required: true
      type: string
    - name: token
      in: path
      required: true
      type: string
  /password-reset/verify-code/{encoded_pk}:
    post:
      operationId: password-reset_verify-code_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/PasswordResetCodeVerify'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/PasswordResetCodeVerify'
      tags:
      - password-reset
    parameters:
    - name: encoded_pk
      in: path
      required: true
      type: string
  /register:
    post:
      operationId: register_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Register'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Register'
      tags:
      - register
    parameters: []
  /register_shelter:
    post:
      operationId: register_shelter_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/RegisterShelter'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/RegisterShelter'
      tags:
      - register_shelter
    parameters: []
  /token-refresh:
    post:
      operationId: token-refresh_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserTokenRefresh'
      responses:
        '200':
          description: Success
          schema:
            type: object
            properties:
              refresh:
                type: string
              access:
                type: string
      tags:
      - token-refresh
    parameters: []
  /user/listings/adoptions:
    get:
      operationId: user_listings_adoptions_list
      description: ''
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/ListingList'
      tags:
      - user
    parameters: []
  /user/listings/adoptions/add:
    post:
      operationId: user_listings_adoptions_add_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/AddAdoptionListing'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/AddAdoptionListing'
      tags:
      - user
    parameters: []
  /user/listings/lost:
    get:
      operationId: user_listings_lost_list
      description: ''
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/ListingList'
      tags:
      - user
    parameters: []
  /user/listings/lost/add:
    post:
      operationId: user_listings_lost_add_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/AddLostListing'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/AddLostListing'
      tags:
      - user
    parameters: []
  /user/me:
    get:
      operationId: user_me_list
      description: ''
      parameters:
      - name: page
        in: query
        description: A page number within the paginated result set.
        required: false
        type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
            - count
            - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/UserGetMe'
      tags:
      - user
      security:
      - Bearer: []
    parameters: []
  /verify:
    post:
      operationId: verify_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Verify'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Verify'
      tags:
      - verify
    parameters: []
definitions:
  Login:
    required:
    - email
    - password
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  PasswordResetConfirm:
    required:
    - new_password
    type: object
    properties:
      new_password:
        title: New password
        type: string
        minLength: 1
  PasswordResetCodeVerify:
    required:
    - reset_code
    type: object
    properties:
      reset_code:
        title: Reset code
        type: string
        pattern: ^\d{6}$
        minLength: 1
  Register:
    required:
    - email
    - first_name
    - last_name
    - password
    type: object
    properties:
      email:
        title: Email
        type: string
        minLength: 1
      first_name:
        title: First name
        type: string
        minLength: 1
      last_name:
        title: Last name
        type: string
        minLength: 1
      phone:
        title: Phone
        type: string
        pattern: ^\+?1?\d{9,15}$
      password:
        title: Password
        type: string
        minLength: 1
  RegisterShelter:
    required:
    - email
    - name
    - registration_number
    - password
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
      name:
        title: Name
        type: string
        minLength: 1
      registration_number:
        title: Registration number
        type: string
        maxLength: 50
        minLength: 1
      phone:
        title: Phone
        type: string
        pattern: ^\+?1?\d{9,15}$
      password:
        title: Password
        type: string
        minLength: 1
  UserTokenRefresh:
    required:
    - refresh_token
    type: object
    properties:
      refresh_token:
        title: Refresh token
        type: string
        minLength: 1
  ListingList:
    required:
    - type
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      name:
        title: Name
        type: string
        maxLength: 100
        x-nullable: true
      age:
        title: Age
        type: string
        readOnly: true
      type:
        title: Type
        type: string
        enum:
        - dog
        - cat
        - parrot
        - turtle
        - rabbit
        - fish
        - hamster
        - other
      breed:
        title: Breed
        type: string
        maxLength: 100
        x-nullable: true
      description:
        title: Description
        type: string
        x-nullable: true
      main_photo_url:
        title: Main photo url
        type: string
        readOnly: true
  AddAdoptionListing:
    required:
    - type
    type: object
    properties:
      name:
        title: Name
        type: string
        maxLength: 100
        x-nullable: true
      type:
        title: Type
        type: string
        enum:
        - dog
        - cat
        - parrot
        - turtle
        - rabbit
        - fish
        - hamster
        - other
      breed:
        title: Breed
        type: string
        maxLength: 100
        x-nullable: true
      birth_date:
        title: Birth date
        type: string
        format: date
        x-nullable: true
      weight:
        title: Weight
        type: number
        x-nullable: true
      gender:
        title: Gender
        type: string
        enum:
        - male
        - female
        x-nullable: true
      description:
        title: Description
        type: string
        x-nullable: true
      is_vaccinated:
        title: Is vaccinated
        type: boolean
        default: false
  AddLostListing:
    required:
    - type
    type: object
    properties:
      name:
        title: Name
        type: string
        maxLength: 100
        x-nullable: true
      type:
        title: Type
        type: string
        enum:
        - dog
        - cat
        - parrot
        - turtle
        - rabbit
        - fish
        - hamster
        - other
      breed:
        title: Breed
        type: string
        maxLength: 100
        x-nullable: true
      birth_date:
        title: Birth date
        type: string
        format: date
        x-nullable: true
      weight:
        title: Weight
        type: number
        x-nullable: true
      gender:
        title: Gender
        type: string
        enum:
        - male
        - female
        x-nullable: true
      description:
        title: Description
        type: string
        x-nullable: true
      is_vaccinated:
        title: Is vaccinated
        type: boolean
        default: false
      last_seen_location_longitude:
        title: Last seen location longitude
        type: string
        format: decimal
      last_seen_location_latitude:
        title: Last seen location latitude
        type: string
        format: decimal
      last_seen_date:
        title: Last seen date
        type: string
        format: date
        x-nullable: true
  UserGetMe:
    required:
    - phone
    - user_type
    type: object
    properties:
      id:
        title: ID
        type: integer
        readOnly: true
      email:
        title: Email address
        type: string
        format: email
        maxLength: 254
      full_name:
        title: Full name
        type: string
        readOnly: true
      date_joined:
        title: Date joined
        type: string
        format: date-time
      phone:
        title: Phone
        type: string
        minLength: 1
      user_type:
        title: User type
        type: string
        minLength: 1
  Verify:
    required:
    - email
    - code
    type: object
    properties:
      email:
        title: Email
        type: string
        format: email
        minLength: 1
      code:
        title: Code
        type: string
        maxLength: 6
        minLength: 1
